/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as receiptNftSol from "./ReceiptNFT.sol";
export type { receiptNftSol };
export type { MyReceiptStamp } from "./MyReceiptStamp";
