/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MyReceiptStamp {
  export type ReceiptStruct = {
    id: BigNumberish;
    creator: AddressLike;
    owner: AddressLike;
    royaltyRecipient: AddressLike;
    text: string;
    createdAt: BigNumberish;
    minted: boolean;
  };

  export type ReceiptStructOutput = [
    id: bigint,
    creator: string,
    owner: string,
    royaltyRecipient: string,
    text: string,
    createdAt: bigint,
    minted: boolean
  ] & {
    id: bigint;
    creator: string;
    owner: string;
    royaltyRecipient: string;
    text: string;
    createdAt: bigint;
    minted: boolean;
  };
}

export interface MyReceiptStampInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_PAGE_SIZE"
      | "MAX_SCAN_SIZE"
      | "MAX_TEXT_LENGTH"
      | "OWNER_ROLE"
      | "VERSION_MAJOR"
      | "VERSION_MINOR"
      | "VERSION_PATCH"
      | "addAdmin"
      | "addOwner"
      | "getAdmins"
      | "getConfig"
      | "getOwners"
      | "getReceipt"
      | "getReceiptsByCreator"
      | "getReceiptsByCreatorDesc"
      | "getReceiptsByOwner"
      | "getReceiptsByOwnerDesc"
      | "getReceiptsByRoyaltyRecipient"
      | "getReceiptsByRoyaltyRecipientDesc"
      | "getReceiptsLatest"
      | "getReceiptsRange"
      | "getReceiptsRangeDesc"
      | "getRoleAdmin"
      | "getRoleMember"
      | "getRoleMemberCount"
      | "getRoleMembers"
      | "getRoyaltyFeeFor"
      | "getStampFeeFor"
      | "getStats"
      | "getVersion"
      | "grantRole"
      | "hasRole"
      | "isAdmin"
      | "isOwner"
      | "lastId"
      | "markMinted"
      | "nftContract"
      | "pageSize"
      | "removeAdmin"
      | "removeOwner"
      | "renounceRole"
      | "revokeRole"
      | "royaltyFee"
      | "setFees"
      | "setNftContract"
      | "setPageSize"
      | "setReceiptRoyaltyRecipient"
      | "setTreasury"
      | "stampFee"
      | "submitReceipt"
      | "submitReceiptFor"
      | "supportsInterface"
      | "totalRoyaltyFee"
      | "totalStampFee"
      | "totalSubmissions"
      | "totalTransfers"
      | "transferReceipt"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesUpdated"
      | "NftContractUpdated"
      | "ReceiptMinted"
      | "ReceiptRoyaltyUpdated"
      | "ReceiptSubmitted"
      | "ReceiptTransferred"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TreasuryUpdated"
      | "VersionInfo"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PAGE_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SCAN_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TEXT_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERSION_MAJOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERSION_MINOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERSION_PATCH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getAdmins", values?: undefined): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByCreator",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByCreatorDesc",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByOwner",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByOwnerDesc",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByRoyaltyRecipient",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsByRoyaltyRecipientDesc",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsLatest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptsRangeDesc",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMembers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoyaltyFeeFor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStampFeeFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lastId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markMinted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pageSize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPageSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiptRoyaltyRecipient",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stampFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitReceipt",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReceiptFor",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRoyaltyFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStampFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSubmissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTransfers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferReceipt",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PAGE_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SCAN_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TEXT_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OWNER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VERSION_MAJOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERSION_MINOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERSION_PATCH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAdmins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByCreatorDesc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByOwnerDesc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByRoyaltyRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsByRoyaltyRecipientDesc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsLatest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptsRangeDesc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoyaltyFeeFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStampFeeFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markMinted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pageSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "royaltyFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPageSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiptRoyaltyRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stampFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReceiptFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRoyaltyFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStampFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace FeesUpdatedEvent {
  export type InputTuple = [
    newStampFee: BigNumberish,
    newRoyaltyFee: BigNumberish
  ];
  export type OutputTuple = [newStampFee: bigint, newRoyaltyFee: bigint];
  export interface OutputObject {
    newStampFee: bigint;
    newRoyaltyFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NftContractUpdatedEvent {
  export type InputTuple = [previousNft: AddressLike, newNft: AddressLike];
  export type OutputTuple = [previousNft: string, newNft: string];
  export interface OutputObject {
    previousNft: string;
    newNft: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptMintedEvent {
  export type InputTuple = [id: BigNumberish, nftContract: AddressLike];
  export type OutputTuple = [id: bigint, nftContract: string];
  export interface OutputObject {
    id: bigint;
    nftContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptRoyaltyUpdatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [id: bigint, creator: string, newRecipient: string];
  export interface OutputObject {
    id: bigint;
    creator: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    owner: AddressLike,
    royaltyRecipient: AddressLike,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    owner: string,
    royaltyRecipient: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    owner: string;
    royaltyRecipient: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptTransferredEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    royaltyRecipient: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    from: string,
    to: string,
    royaltyRecipient: string
  ];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
    royaltyRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [
    previousTreasury: AddressLike,
    newTreasury: AddressLike
  ];
  export type OutputTuple = [previousTreasury: string, newTreasury: string];
  export interface OutputObject {
    previousTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VersionInfoEvent {
  export type InputTuple = [
    major: BigNumberish,
    minor: BigNumberish,
    patch: BigNumberish
  ];
  export type OutputTuple = [major: bigint, minor: bigint, patch: bigint];
  export interface OutputObject {
    major: bigint;
    minor: bigint;
    patch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MyReceiptStamp extends BaseContract {
  connect(runner?: ContractRunner | null): MyReceiptStamp;
  waitForDeployment(): Promise<this>;

  interface: MyReceiptStampInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_PAGE_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_SCAN_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_TEXT_LENGTH: TypedContractMethod<[], [bigint], "view">;

  OWNER_ROLE: TypedContractMethod<[], [string], "view">;

  VERSION_MAJOR: TypedContractMethod<[], [bigint], "view">;

  VERSION_MINOR: TypedContractMethod<[], [bigint], "view">;

  VERSION_PATCH: TypedContractMethod<[], [bigint], "view">;

  addAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  addOwner: TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getAdmins: TypedContractMethod<[], [string[]], "view">;

  getConfig: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        contractOwner: string;
        contractAdmin: string;
        contractTreasury: string;
        contractNft: string;
        currentStampFee: bigint;
        currentRoyaltyFee: bigint;
        currentPageSize: bigint;
      }
    ],
    "view"
  >;

  getOwners: TypedContractMethod<[], [string[]], "view">;

  getReceipt: TypedContractMethod<
    [id: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput],
    "view"
  >;

  getReceiptsByCreator: TypedContractMethod<
    [creator: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getReceiptsByCreatorDesc: TypedContractMethod<
    [
      creator: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;

  getReceiptsByOwner: TypedContractMethod<
    [owner: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getReceiptsByOwnerDesc: TypedContractMethod<
    [
      owner: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;

  getReceiptsByRoyaltyRecipient: TypedContractMethod<
    [recipient: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getReceiptsByRoyaltyRecipientDesc: TypedContractMethod<
    [
      recipient: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;

  getReceiptsLatest: TypedContractMethod<
    [limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getReceiptsRange: TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getReceiptsRangeDesc: TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoleMember: TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;

  getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], "view">;

  getRoleMembers: TypedContractMethod<[role: BytesLike], [string[]], "view">;

  getRoyaltyFeeFor: TypedContractMethod<
    [id: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;

  getStampFeeFor: TypedContractMethod<[sender: AddressLike], [bigint], "view">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        lastReceiptId: bigint;
        submissions: bigint;
        transfers: bigint;
        totalStampFees: bigint;
        totalRoyaltyFees: bigint;
      }
    ],
    "view"
  >;

  getVersion: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[who: AddressLike], [boolean], "view">;

  isOwner: TypedContractMethod<[who: AddressLike], [boolean], "view">;

  lastId: TypedContractMethod<[], [bigint], "view">;

  markMinted: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  nftContract: TypedContractMethod<[], [string], "view">;

  pageSize: TypedContractMethod<[], [bigint], "view">;

  removeAdmin: TypedContractMethod<
    [adminToRemove: AddressLike],
    [void],
    "nonpayable"
  >;

  removeOwner: TypedContractMethod<
    [ownerToRemove: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  royaltyFee: TypedContractMethod<[], [bigint], "view">;

  setFees: TypedContractMethod<
    [newStampFee: BigNumberish, newRoyaltyFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setNftContract: TypedContractMethod<
    [newNftContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setPageSize: TypedContractMethod<
    [newSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReceiptRoyaltyRecipient: TypedContractMethod<
    [id: BigNumberish, newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  stampFee: TypedContractMethod<[], [bigint], "view">;

  submitReceipt: TypedContractMethod<[text: string], [bigint], "payable">;

  submitReceiptFor: TypedContractMethod<
    [text: string, recipient: AddressLike],
    [bigint],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalRoyaltyFee: TypedContractMethod<[], [bigint], "view">;

  totalStampFee: TypedContractMethod<[], [bigint], "view">;

  totalSubmissions: TypedContractMethod<[], [bigint], "view">;

  totalTransfers: TypedContractMethod<[], [bigint], "view">;

  transferReceipt: TypedContractMethod<
    [id: BigNumberish, newOwner: AddressLike],
    [void],
    "payable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_PAGE_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCAN_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TEXT_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OWNER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERSION_MAJOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION_MINOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION_PATCH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addOwner"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAdmins"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        contractOwner: string;
        contractAdmin: string;
        contractTreasury: string;
        contractNft: string;
        currentStampFee: bigint;
        currentRoyaltyFee: bigint;
        currentPageSize: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [id: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByCreator"
  ): TypedContractMethod<
    [creator: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByCreatorDesc"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByOwner"
  ): TypedContractMethod<
    [owner: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByOwnerDesc"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByRoyaltyRecipient"
  ): TypedContractMethod<
    [recipient: AddressLike, startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsByRoyaltyRecipientDesc"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      startId: BigNumberish,
      limit: BigNumberish,
      maxScan: BigNumberish
    ],
    [[MyReceiptStamp.ReceiptStructOutput[], bigint] & { nextStartId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsLatest"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsRange"
  ): TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptsRangeDesc"
  ): TypedContractMethod<
    [startId: BigNumberish, limit: BigNumberish],
    [MyReceiptStamp.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleMember"
  ): TypedContractMethod<
    [role: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleMemberCount"
  ): TypedContractMethod<[role: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleMembers"
  ): TypedContractMethod<[role: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoyaltyFeeFor"
  ): TypedContractMethod<
    [id: BigNumberish, sender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStampFeeFor"
  ): TypedContractMethod<[sender: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        lastReceiptId: bigint;
        submissions: bigint;
        transfers: bigint;
        totalStampFees: bigint;
        totalRoyaltyFees: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[who: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[who: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markMinted"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pageSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[adminToRemove: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeOwner"
  ): TypedContractMethod<[ownerToRemove: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "royaltyFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [newStampFee: BigNumberish, newRoyaltyFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNftContract"
  ): TypedContractMethod<[newNftContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPageSize"
  ): TypedContractMethod<[newSize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReceiptRoyaltyRecipient"
  ): TypedContractMethod<
    [id: BigNumberish, newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stampFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitReceipt"
  ): TypedContractMethod<[text: string], [bigint], "payable">;
  getFunction(
    nameOrSignature: "submitReceiptFor"
  ): TypedContractMethod<
    [text: string, recipient: AddressLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalRoyaltyFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStampFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSubmissions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTransfers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferReceipt"
  ): TypedContractMethod<
    [id: BigNumberish, newOwner: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesUpdated"
  ): TypedContractEvent<
    FeesUpdatedEvent.InputTuple,
    FeesUpdatedEvent.OutputTuple,
    FeesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NftContractUpdated"
  ): TypedContractEvent<
    NftContractUpdatedEvent.InputTuple,
    NftContractUpdatedEvent.OutputTuple,
    NftContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptMinted"
  ): TypedContractEvent<
    ReceiptMintedEvent.InputTuple,
    ReceiptMintedEvent.OutputTuple,
    ReceiptMintedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptRoyaltyUpdated"
  ): TypedContractEvent<
    ReceiptRoyaltyUpdatedEvent.InputTuple,
    ReceiptRoyaltyUpdatedEvent.OutputTuple,
    ReceiptRoyaltyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptSubmitted"
  ): TypedContractEvent<
    ReceiptSubmittedEvent.InputTuple,
    ReceiptSubmittedEvent.OutputTuple,
    ReceiptSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptTransferred"
  ): TypedContractEvent<
    ReceiptTransferredEvent.InputTuple,
    ReceiptTransferredEvent.OutputTuple,
    ReceiptTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VersionInfo"
  ): TypedContractEvent<
    VersionInfoEvent.InputTuple,
    VersionInfoEvent.OutputTuple,
    VersionInfoEvent.OutputObject
  >;

  filters: {
    "FeesUpdated(uint256,uint256)": TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;
    FeesUpdated: TypedContractEvent<
      FeesUpdatedEvent.InputTuple,
      FeesUpdatedEvent.OutputTuple,
      FeesUpdatedEvent.OutputObject
    >;

    "NftContractUpdated(address,address)": TypedContractEvent<
      NftContractUpdatedEvent.InputTuple,
      NftContractUpdatedEvent.OutputTuple,
      NftContractUpdatedEvent.OutputObject
    >;
    NftContractUpdated: TypedContractEvent<
      NftContractUpdatedEvent.InputTuple,
      NftContractUpdatedEvent.OutputTuple,
      NftContractUpdatedEvent.OutputObject
    >;

    "ReceiptMinted(uint256,address)": TypedContractEvent<
      ReceiptMintedEvent.InputTuple,
      ReceiptMintedEvent.OutputTuple,
      ReceiptMintedEvent.OutputObject
    >;
    ReceiptMinted: TypedContractEvent<
      ReceiptMintedEvent.InputTuple,
      ReceiptMintedEvent.OutputTuple,
      ReceiptMintedEvent.OutputObject
    >;

    "ReceiptRoyaltyUpdated(uint256,address,address)": TypedContractEvent<
      ReceiptRoyaltyUpdatedEvent.InputTuple,
      ReceiptRoyaltyUpdatedEvent.OutputTuple,
      ReceiptRoyaltyUpdatedEvent.OutputObject
    >;
    ReceiptRoyaltyUpdated: TypedContractEvent<
      ReceiptRoyaltyUpdatedEvent.InputTuple,
      ReceiptRoyaltyUpdatedEvent.OutputTuple,
      ReceiptRoyaltyUpdatedEvent.OutputObject
    >;

    "ReceiptSubmitted(uint256,address,address,address,uint256)": TypedContractEvent<
      ReceiptSubmittedEvent.InputTuple,
      ReceiptSubmittedEvent.OutputTuple,
      ReceiptSubmittedEvent.OutputObject
    >;
    ReceiptSubmitted: TypedContractEvent<
      ReceiptSubmittedEvent.InputTuple,
      ReceiptSubmittedEvent.OutputTuple,
      ReceiptSubmittedEvent.OutputObject
    >;

    "ReceiptTransferred(uint256,address,address,address)": TypedContractEvent<
      ReceiptTransferredEvent.InputTuple,
      ReceiptTransferredEvent.OutputTuple,
      ReceiptTransferredEvent.OutputObject
    >;
    ReceiptTransferred: TypedContractEvent<
      ReceiptTransferredEvent.InputTuple,
      ReceiptTransferredEvent.OutputTuple,
      ReceiptTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "VersionInfo(uint256,uint256,uint256)": TypedContractEvent<
      VersionInfoEvent.InputTuple,
      VersionInfoEvent.OutputTuple,
      VersionInfoEvent.OutputObject
    >;
    VersionInfo: TypedContractEvent<
      VersionInfoEvent.InputTuple,
      VersionInfoEvent.OutputTuple,
      VersionInfoEvent.OutputObject
    >;
  };
}
