/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as receiptNftSol from "./ReceiptNFT.sol";
export { MyReceiptStamp__factory } from "./MyReceiptStamp__factory";
