/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReceiptStamp__factory } from "./IReceiptStamp__factory";
export { ReceiptNFT__factory } from "./ReceiptNFT__factory";
